package org.oasis_open.docs.wsn.brw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-11-13T15:21:18.324+08:00
 * Generated source version: 2.3.2
 */

@WebFault(name = "ResourceNotDestroyedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
public class ResourceNotDestroyedFault extends Exception {
	public static final long serialVersionUID = 20121113152118L;

	private org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault;

	public ResourceNotDestroyedFault() {
		super();
	}

	public ResourceNotDestroyedFault(String message) {
		super(message);
	}

	public ResourceNotDestroyedFault(String message, Throwable cause) {
		super(message, cause);
	}

	public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault) {
		super(message);
		this.resourceNotDestroyedFault = resourceNotDestroyedFault;
	}

	public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault, Throwable cause) {
		super(message, cause);
		this.resourceNotDestroyedFault = resourceNotDestroyedFault;
	}

	public org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType getFaultInfo() {
		return this.resourceNotDestroyedFault;
	}
}
