
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-11-13T15:21:18.346+08:00
 * Generated source version: 2.3.2
 * 
 */

@WebFault(name = "ResourceUnavailableFault", targetNamespace = "http://docs.oasis-open.org/wsrf/r-2")
public class ResourceUnavailableFault extends Exception {
    public static final long serialVersionUID = 20121113152118L;
    
    private org.oasis_open.docs.wsrf.r_2.ResourceUnavailableFaultType resourceUnavailableFault;

    public ResourceUnavailableFault() {
        super();
    }
    
    public ResourceUnavailableFault(String message) {
        super(message);
    }
    
    public ResourceUnavailableFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceUnavailableFault(String message, org.oasis_open.docs.wsrf.r_2.ResourceUnavailableFaultType resourceUnavailableFault) {
        super(message);
        this.resourceUnavailableFault = resourceUnavailableFault;
    }

    public ResourceUnavailableFault(String message, org.oasis_open.docs.wsrf.r_2.ResourceUnavailableFaultType resourceUnavailableFault, Throwable cause) {
        super(message, cause);
        this.resourceUnavailableFault = resourceUnavailableFault;
    }

    public org.oasis_open.docs.wsrf.r_2.ResourceUnavailableFaultType getFaultInfo() {
        return this.resourceUnavailableFault;
    }
}
