package org.oasis_open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-11-13T15:21:18.367+08:00
 * Generated source version: 2.3.2
 */

@WebFault(name = "InvalidProducerPropertiesExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidProducerPropertiesExpressionFault extends Exception {
	public static final long serialVersionUID = 20121113152118L;

	private org.oasis_open.docs.wsn.b_2.InvalidProducerPropertiesExpressionFaultType invalidProducerPropertiesExpressionFault;

	public InvalidProducerPropertiesExpressionFault() {
		super();
	}

	public InvalidProducerPropertiesExpressionFault(String message) {
		super(message);
	}

	public InvalidProducerPropertiesExpressionFault(String message, Throwable cause) {
		super(message, cause);
	}

	public InvalidProducerPropertiesExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidProducerPropertiesExpressionFaultType invalidProducerPropertiesExpressionFault) {
		super(message);
		this.invalidProducerPropertiesExpressionFault = invalidProducerPropertiesExpressionFault;
	}

	public InvalidProducerPropertiesExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidProducerPropertiesExpressionFaultType invalidProducerPropertiesExpressionFault, Throwable cause) {
		super(message, cause);
		this.invalidProducerPropertiesExpressionFault = invalidProducerPropertiesExpressionFault;
	}

	public org.oasis_open.docs.wsn.b_2.InvalidProducerPropertiesExpressionFaultType getFaultInfo() {
		return this.invalidProducerPropertiesExpressionFault;
	}
}
