
package org.oasis_open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-11-13T15:21:18.327+08:00
 * Generated source version: 2.3.2
 * 
 */

@WebFault(name = "UnableToCreatePullPointFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnableToCreatePullPointFault extends Exception {
    public static final long serialVersionUID = 20121113152118L;
    
    private org.oasis_open.docs.wsn.b_2.UnableToCreatePullPointFaultType unableToCreatePullPointFault;

    public UnableToCreatePullPointFault() {
        super();
    }
    
    public UnableToCreatePullPointFault(String message) {
        super(message);
    }
    
    public UnableToCreatePullPointFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToCreatePullPointFault(String message, org.oasis_open.docs.wsn.b_2.UnableToCreatePullPointFaultType unableToCreatePullPointFault) {
        super(message);
        this.unableToCreatePullPointFault = unableToCreatePullPointFault;
    }

    public UnableToCreatePullPointFault(String message, org.oasis_open.docs.wsn.b_2.UnableToCreatePullPointFaultType unableToCreatePullPointFault, Throwable cause) {
        super(message, cause);
        this.unableToCreatePullPointFault = unableToCreatePullPointFault;
    }

    public org.oasis_open.docs.wsn.b_2.UnableToCreatePullPointFaultType getFaultInfo() {
        return this.unableToCreatePullPointFault;
    }
}
