package org.apache.servicemix.wsn.router.router;

import java.util.Timer;

/**
 * Created by Niu on 2015/12/22.
 */
public class refreshGloble {

	public static void main(String[] args) {
		// TODO todo.generated by zoer
		Timer timer = new Timer();
//        timer.schedule(new GlobleUtil(), 1000, 2000);
	}
}
