package org.oasis_open.docs.wsn.bw_2;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-11-13T15:21:18.418+08:00
 * Generated source version: 2.3.2
 */

@WebService(targetNamespace = "http://docs.oasis-open.org/wsn/bw-2", name = "PullPoint")
@XmlSeeAlso({org.oasis_open.docs.wsn.t_1.ObjectFactory.class, org.oasis_open.docs.wsn.br_2.ObjectFactory.class, org.oasis_open.docs.wsrf.r_2.ObjectFactory.class, org.oasis_open.docs.wsn.b_2.ObjectFactory.class, org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class, org.oasis_open.docs.wsrf.rp_2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PullPoint {

	@WebResult(name = "DestroyPullPointResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "DestroyPullPointResponse")
	@WebMethod(operationName = "DestroyPullPoint")
	public org.oasis_open.docs.wsn.b_2.DestroyPullPointResponse destroyPullPoint(
			@WebParam(partName = "DestroyPullPointRequest", name = "DestroyPullPoint", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
			org.oasis_open.docs.wsn.b_2.DestroyPullPoint destroyPullPointRequest
	) throws org.oasis_open.docs.wsrf.rw_2.ResourceUnknownFault, UnableToDestroyPullPointFault;

	@Oneway
	@WebMethod(operationName = "Notify")
	public void notify(
			@WebParam(partName = "Notify", name = "Notify", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
			org.oasis_open.docs.wsn.b_2.Notify notify
	);

	@WebResult(name = "GetMessagesResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "GetMessagesResponse")
	@WebMethod(operationName = "GetMessages")
	public org.oasis_open.docs.wsn.b_2.GetMessagesResponse getMessages(
			@WebParam(partName = "GetMessagesRequest", name = "GetMessages", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
			org.oasis_open.docs.wsn.b_2.GetMessages getMessagesRequest
	) throws org.oasis_open.docs.wsrf.rw_2.ResourceUnknownFault, UnableToGetMessagesFault;
}
